import {
  Home,
  TrendingUp,
  Briefcase,
  Percent,
  Calculator,
  DollarSign,
  BarChart,
  Youtube,
  User,
  Zap,
  GraduationCap,
  CalendarDays,
  PiggyBank,
  CreditCard,
  Music2,
  Car,
  TrendingDown,
  Wallet,
  Receipt,
  Clock,
  Timer,
  BookOpen,
  Construction,
  Square,
  Circle,
  Hash,
  Layers,
  ArrowLeftRight,
  Lock,
  Baby,
  Calendar,
  Activity,
  LucideIcon
} from 'lucide-react';

export interface CalculatorInfo {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  path: string;
  category: 'finance' | 'health' | 'content' | 'education' | 'tools';
}

export const calculators: CalculatorInfo[] = [
  {
    id: 'body-fat',
    name: 'Body Fat Calculator',
    description: 'Estimate your body fat percentage using the U.S. Navy method and track your fitness category.',
    icon: Activity,
    path: '/calculators/body-fat',
    category: 'health',
  },
  {
    id: 'due-date',
    name: 'Due Date Calculator',
    description: 'Find your estimated due date using multiple methods including last period, ultrasound, or IVF transfer details.',
    icon: Calendar,
    path: '/calculators/due-date',
    category: 'health',
  },
  {
    id: 'pregnancy',
    name: 'Pregnancy Calculator',
    description: 'Calculate your due date, current week, and track major milestones throughout your pregnancy journey.',
    icon: Baby,
    path: '/calculators/pregnancy',
    category: 'health',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Create secure, random passwords with custom lengths and character sets for maximum online safety.',
    icon: Lock,
    path: '/calculators/password-generator',
    category: 'tools',
  },
  {
    id: 'conversion',
    name: 'Conversion Calculator',
    description: 'Convert units for length, temperature, area, volume, and weight with high precision.',
    icon: ArrowLeftRight,
    path: '/calculators/conversion',
    category: 'tools',
  },
  {
    id: 'concrete',
    name: 'Concrete Calculator',
    description: 'Calculate the volume and weight of concrete needed for slabs, footings, columns, and stairs.',
    icon: Construction,
    path: '/calculators/concrete',
    category: 'tools',
  },
  {
    id: 'hours',
    name: 'Hours Calculator',
    description: 'Calculate the number of hours and minutes between two times or two specific dates.',
    icon: Clock,
    path: '/calculators/hours',
    category: 'tools',
  },
  {
    id: 'time-card',
    name: 'Time Card Calculator',
    description: 'Generate a professional weekly time card with break deductions and decimal conversions.',
    icon: Timer,
    path: '/calculators/time-card',
    category: 'tools',
  },
  {
    id: 'inflation',
    name: 'Inflation Calculator',
    description: 'Calculate the purchasing power of money over time using historical U.S. CPI data or flat inflation rates.',
    icon: TrendingDown,
    path: '/calculators/inflation',
    category: 'finance',
  },
  {
    id: 'investment',
    name: 'Investment Calculator',
    description: 'A professional tool to solve for any investment variable: end amount, contributions, rate, or length.',
    icon: TrendingUp,
    path: '/calculators/investment',
    category: 'finance',
  },
  {
    id: 'salary',
    name: 'Salary Calculator',
    description: 'Convert your pay between hourly, weekly, monthly, and yearly periods with holiday adjustments.',
    icon: Wallet,
    path: '/calculators/salary',
    category: 'finance',
  },
  {
    id: 'payment',
    name: 'Payment Calculator',
    description: 'Calculate monthly payments or payoff terms for any loan or credit card.',
    icon: CreditCard,
    path: '/calculators/payment',
    category: 'finance',
  },
  {
    id: 'interest',
    name: 'Interest Calculator',
    description: 'Calculate growth with schedules for simple and compound interest.',
    icon: Calculator,
    path: '/calculators/interest',
    category: 'finance',
  },
  {
    id: 'interest-rate',
    name: 'Interest Rate Calculator',
    description: 'Solve for the interest rate required to reach a specific financial goal.',
    icon: Percent,
    path: '/calculators/interest-rate',
    category: 'finance',
  },
  {
    id: 'sales-tax',
    name: 'Sales Tax Calculator',
    description: 'Calculate sales tax or determine the original price of an item from its total.',
    icon: Receipt,
    path: '/calculators/sales-tax',
    category: 'finance',
  },
  {
    id: 'mortgage',
    name: 'Mortgage Calculator',
    description: 'Calculate monthly payments, interest, and payoff dates.',
    icon: Home,
    path: '/calculators/mortgage',
    category: 'finance',
  },
  {
    id: 'auto-loan',
    name: 'Auto Loan Calculator',
    description: 'Estimate monthly car payments including trade-ins, taxes, and fees.',
    icon: Car,
    path: '/calculators/auto-loan',
    category: 'finance',
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Determine the future value of your investments over time.',
    icon: TrendingUp,
    path: '/calculators/compound-interest',
    category: 'finance',
  },
  {
    id: 'retirement',
    name: 'Retirement Planner',
    description: 'Estimate your nest egg and plan for a comfortable future.',
    icon: Briefcase,
    path: '/calculators/retirement',
    category: 'finance',
  },
  {
    id: 'tax',
    name: 'Tax Calculator',
    description: 'Estimated income tax based on specified rules and income.',
    icon: Percent,
    path: '/calculators/tax',
    category: 'finance',
  },
  {
    id: 'currency',
    name: 'Currency Converter',
    description: 'Quick conversion between global currencies with recent rates.',
    icon: DollarSign,
    path: '/calculators/currency',
    category: 'finance',
  },
  {
    id: 'loan-interest',
    name: 'Loan Interest',
    description: 'Calculate total interest and payment schedules for any loan.',
    icon: Calculator,
    path: '/calculators/loan-interest',
    category: 'finance',
  },
  {
    id: 'savings',
    name: 'Savings Goal',
    description: 'Plan how much you need to save to reach your target balance.',
    icon: PiggyBank,
    path: '/calculators/savings',
    category: 'finance',
  },
  {
    id: 'debt-payoff',
    name: 'Debt Payoff',
    description: 'Calculate how long it takes to clear your debt and interest saved.',
    icon: CreditCard,
    path: '/calculators/debt-payoff',
    category: 'finance',
  },
  {
    id: 'roi',
    name: 'ROI Calculator',
    description: 'Measure the profitability and gains of your investments.',
    icon: BarChart,
    path: '/calculators/roi',
    category: 'finance',
  },
  {
    id: 'youtube-revenue',
    name: 'YouTube Revenue',
    description: 'Estimate potential channel earnings based on views and CPM.',
    icon: Youtube,
    path: '/calculators/youtube-revenue',
    category: 'content',
  },
  {
    id: 'tiktok-revenue',
    name: 'TikTok Revenue',
    description: 'Estimate TikTok creator fund and brand deal earnings.',
    icon: Music2,
    path: '/calculators/tiktok-revenue',
    category: 'content',
  },
  {
    id: 'tiktok-engagement',
    name: 'TikTok Engagement',
    description: 'Measure likes, comments, and shares relative to followers.',
    icon: TrendingUp,
    path: '/calculators/tiktok-engagement',
    category: 'content',
  },
  {
    id: 'bmi',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index to assess weight categories.',
    icon: User,
    path: '/calculators/bmi',
    category: 'health',
  },
  {
    id: 'calorie',
    name: 'Calorie Calculator',
    description: 'Estimate daily caloric needs based on activity and body metrics.',
    icon: Zap,
    path: '/calculators/calorie',
    category: 'health',
  },
  {
    id: 'gpa',
    name: 'GPA Calculator',
    description: 'Calculate your semester or cumulative GPA easily.',
    icon: GraduationCap,
    path: '/calculators/gpa',
    category: 'education',
  },
  {
    id: 'gpa-to-percentage',
    name: 'GPA to Percentage',
    description: 'Convert 4.0 or 5.0 GPA scale to percentage values.',
    icon: Percent,
    path: '/calculators/gpa-to-percentage',
    category: 'education',
  },
  {
    id: 'grade',
    name: 'Grade Calculator',
    description: 'Calculate your current course grade or find out what you need on your final exam.',
    icon: BookOpen,
    path: '/calculators/grade',
    category: 'education',
  },
  {
    id: 'age',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days.',
    icon: User,
    path: '/calculators/age',
    category: 'tools',
  },
  {
    id: 'date',
    name: 'Date Calculator',
    description: 'Add or subtract days from a date or find duration.',
    icon: CalendarDays,
    path: '/calculators/date',
    category: 'tools',
  },
  {
    id: 'time',
    name: 'Time Calculator',
    description: 'A comprehensive tool for time arithmetic, date offset, and time expression parsing.',
    icon: Clock,
    path: '/calculators/time',
    category: 'tools',
  },
];
