import {
  Home,
  TrendingUp,
  Briefcase,
  Percent,
  Calculator,
  DollarSign,
  BarChart,
  Youtube,
  User,
  Zap,
  GraduationCap,
  CalendarDays,
  PiggyBank,
  CreditCard,
  Music2,
  Car,
  TrendingDown,
  LucideIcon
} from 'lucide-react';

export interface CalculatorInfo {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  path: string;
  category: 'finance' | 'health' | 'content' | 'education' | 'tools';
}

export const calculators: CalculatorInfo[] = [
  {
    id: 'investment',
    name: 'Investment Calculator',
    description: 'A professional tool to solve for any investment variable: end amount, contributions, rate, or length.',
    icon: TrendingUp,
    path: '/calculators/investment',
    category: 'finance',
  },
  {
    id: 'payment',
    name: 'Payment Calculator',
    description: 'Calculate monthly payments or payoff terms for any loan or credit card.',
    icon: CreditCard,
    path: '/calculators/payment',
    category: 'finance',
  },
  {
    id: 'interest',
    name: 'Interest Calculator',
    description: 'Calculate growth with schedules for simple and compound interest.',
    icon: Calculator,
    path: '/calculators/interest',
    category: 'finance',
  },
  {
    id: 'mortgage',
    name: 'Mortgage Calculator',
    description: 'Calculate monthly payments, interest, and payoff dates.',
    icon: Home,
    path: '/calculators/mortgage',
    category: 'finance',
  },
  {
    id: 'auto-loan',
    name: 'Auto Loan Calculator',
    description: 'Estimate monthly car payments including trade-ins, taxes, and fees.',
    icon: Car,
    path: '/calculators/auto-loan',
    category: 'finance',
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Determine the future value of your investments over time.',
    icon: TrendingUp,
    path: '/calculators/compound-interest',
    category: 'finance',
  },
  {
    id: 'retirement',
    name: 'Retirement Planner',
    description: 'Estimate your nest egg and plan for a comfortable future.',
    icon: Briefcase,
    path: '/calculators/retirement',
    category: 'finance',
  },
  {
    id: 'tax',
    name: 'Tax Calculator',
    description: 'Estimated income tax based on specified rules and income.',
    icon: Percent,
    path: '/calculators/tax',
    category: 'finance',
  },
  {
    id: 'currency',
    name: 'Currency Converter',
    description: 'Quick conversion between global currencies with recent rates.',
    icon: DollarSign,
    path: '/calculators/currency',
    category: 'finance',
  },
  {
    id: 'loan-interest',
    name: 'Loan Interest',
    description: 'Calculate total interest and payment schedules for any loan.',
    icon: Calculator,
    path: '/calculators/loan-interest',
    category: 'finance',
  },
  {
    id: 'savings',
    name: 'Savings Goal',
    description: 'Plan how much you need to save to reach your target balance.',
    icon: PiggyBank,
    path: '/calculators/savings',
    category: 'finance',
  },
  {
    id: 'debt-payoff',
    name: 'Debt Payoff',
    description: 'Calculate how long it takes to clear your debt and interest saved.',
    icon: CreditCard,
    path: '/calculators/debt-payoff',
    category: 'finance',
  },
  {
    id: 'roi',
    name: 'ROI Calculator',
    description: 'Measure the profitability and gains of your investments.',
    icon: BarChart,
    path: '/calculators/roi',
    category: 'finance',
  },
  {
    id: 'youtube-revenue',
    name: 'YouTube Revenue',
    description: 'Estimate potential channel earnings based on views and CPM.',
    icon: Youtube,
    path: '/calculators/youtube-revenue',
    category: 'content',
  },
  {
    id: 'tiktok-revenue',
    name: 'TikTok Revenue',
    description: 'Estimate TikTok creator fund and brand deal earnings.',
    icon: Music2,
    path: '/calculators/tiktok-revenue',
    category: 'content',
  },
  {
    id: 'tiktok-engagement',
    name: 'TikTok Engagement',
    description: 'Measure likes, comments, and shares relative to followers.',
    icon: TrendingUp,
    path: '/calculators/tiktok-engagement',
    category: 'content',
  },
  {
    id: 'bmi',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index to assess weight categories.',
    icon: User,
    path: '/calculators/bmi',
    category: 'health',
  },
  {
    id: 'calorie',
    name: 'Calorie Calculator',
    description: 'Estimate daily caloric needs based on activity and body metrics.',
    icon: Zap,
    path: '/calculators/calorie',
    category: 'health',
  },
  {
    id: 'gpa',
    name: 'GPA Calculator',
    description: 'Calculate your semester or cumulative GPA easily.',
    icon: GraduationCap,
    path: '/calculators/gpa',
    category: 'education',
  },
  {
    id: 'gpa-to-percentage',
    name: 'GPA to Percentage',
    description: 'Convert 4.0 or 5.0 GPA scale to percentage values.',
    icon: Percent,
    path: '/calculators/gpa-to-percentage',
    category: 'education',
  },
  {
    id: 'age',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days.',
    icon: User,
    path: '/calculators/age',
    category: 'tools',
  },
  {
    id: 'date',
    name: 'Date Calculator',
    description: 'Add or subtract days from a date or find duration.',
    icon: CalendarDays,
    path: '/calculators/date',
    category: 'tools',
  },
];
